apiVersion: v1
kind: Service
metadata:
  name: remo-api-deployment
  namespace: remo-api-distribution
spec:
  selector:
    app: remo-api-distribution #app-name
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 31765 #port to be define
  type: NodePort
