apiVersion: v1
kind: Service
metadata:
  name: remo-api-distribution-service
  namespace: remo-api-distribution
spec:
  selector:
    app: api-distribution
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2525
      nodePort: 32023 
  type: NodePort
